# -*- coding: utf-8 -*-
"""avaliador_números_max.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4ufkWItM40wHTac6ADh0OGWHuXWk9Fj
"""

num01 = float(input(f"digite o priemiro número: "))
num02 = float(input(f"digite o segundo  número: "))
num03 = float(input(f"digite o terceiro número: "))
num04 = float(input(f"digite o quarto   número: "))
num05 = float(input(f"digite o quinto   número: "))


maior = max(num01, num02, num03, num04, num05)

print(f"O maior número é: {maior}")

