# -*- coding: utf-8 -*-
"""comparador_números_if.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cYyWtFTgZ4Bul5HJizD3ImMJlNIBr-m
"""

num01 = float(input(f"digite o primeiro número: "))
 num02 = float(input(f"digite o segundo  número: "))

if num01 > num02:
  print(f"O {num01} é o maior!")
elif num01 == num02:
  print(F"Os dois números são iguais!")
else:
  print(f"O {num02} é o maior!")

